version: '1'
services:
    tomcat:
      image: tomcat:8.0
      ports:
        - "8888:8080"
    jenkins:
      image: jenkins
      ports:
        - "80:8080"
    gogs:
      image: gogs:gogs
      ports:
        - "10022:22"
        - "10080:3000"
