# Version 0.1
# http://tecadmin.net/install-zabbix-network-monitoring-on-centos-rhel-and-fedora/
FROM centos:centos7
MAINTAINER Iain Black
ENV REFRESHED_AT 2015-03-19
# Do this or get a "Failed to get D-Bus connection: Operation not permitted" message
ENV container=docker

# Install Zabbix release packages.
RUN yum install -y http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm

# Refresh
RUN yum update -y

# Install Tools
RUN yum -y  install \
            monit \
            nmap  \
            traceroute \
            wget  \
            nano

# Install Pre-Reqs
RUN yum install -y  httpd \
                    httpd-devel \
                    mariadb \
                    mariadb-server \
                    php \
                    php-cli \
                    php-common \
                    php-devel \
                    php-pear \
                    php-gd \
                    php-mbstring \
                    php-mysql \
                    php-xml

RUN yum install -y  zabbix-agent \
                    zabbix-server \
                    zabbix-server-mysql \
                    zabbix-web \
                    zabbix-web-mysql \
                    zabbix-agent \
                    zabbix-java-gateway \
                    zabbix-sender

#Amend the php config file
RUN sed -i -e 's/# php_value date.timezone Europe\/Riga/php_value date.timezone Europe\/Riga/g'  /etc/httpd/conf.d/zabbix.conf

# Start Services
RUN systemctl start httpd
RUN systemctl enable httpd
RUN systemctl start mariadb
RUN systemctl enable mariadb

COPY ./createdb.sh /root/createdb.sh
RUN /root/createdb.sh zabbix zabbix zabbix

EXPOSE 10051 10052 80 2812

CMD ["run"]