# Version 0.1

FROM centos:centos7
MAINTAINER Iain Black
ENV REFRESHED_AT 2015-03-19

# Install Zabbix release packages.
RUN yum install -y http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
# Refresh
RUN yum makecache
