# Version 0.2
# http://tecadmin.net/install-zabbix-network-monitoring-on-centos-rhel-and-fedora/
FROM centos:centos7
MAINTAINER Iain Black
ENV REFRESHED_AT 2015-03-19
# Do this or get a "Failed to get D-Bus connection: Operation not permitted" message
#ENV container=docker

# Install Zabbix release packages.
RUN yum install -y http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm && \
                   yum update -y && \
                   yum -y install \
                          monit \
                          nmap  \
                          traceroute \
                          wget  \
                          nano \
                          httpd \
                          httpd-devel \
                          mariadb \
                          mariadb-server \
                          php \
                          php-cli \
                          php-common \
                          php-devel \
                          php-pear \
                          php-gd \
                          php-mbstring \
                          php-mysql \
                          php-xml \
                          zabbix-agent \
                          zabbix-server \
                          zabbix-server-mysql \
                          zabbix-web \
                          zabbix-web-mysql \
                          zabbix-agent \
                          zabbix-java-gateway \
                          zabbix-sender && \
                    yum clean all

#Amend the php config file
RUN sed -i -e 's/# php_value date.timezone Europe\/Riga/php_value date.timezone Europe\/Riga/g'  /etc/httpd/conf.d/zabbix.conf

# Start Services
CMD ["systemctl", "start",  "httpd"]
CMD ["systemctl", "enable",  "httpd"]
CMD ["systemctl", "start",  "mariadb"]
CMD ["systemctl", "enable",  "mariadb"]

# http://www.bluepiccadilly.com/2011/12/creating-mysql-database-and-user-command-line-and-bash-script-automate-process
COPY ./createdb.sh /root/createdb.sh
#RUN chmod +x /root/createdb.sh
#CMD ["/root/createdb.sh", "zabbix", "zabbix", "zabbix"]

EXPOSE 10051 10052 80 2812
ENTRYPOINT ["/usr/bin/watch", "/dev/null"]
